server:
  port: 8762

spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://localhost:3306/tensquare_friend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: MySQL
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/